/* Main.c file generated by New Project wizard
 *
 * Created:   Sat Feb 6 2021
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
void delay()
{
   unsigned int j;
   for(j=0;j<1257;j++);
   }
void main(void)
 { 
   P1=0xff;
   while (1)
   {
      P3=P1;
   }
 }
 