/* Main.c file generated by New Project wizard
 *
 * Created:   Sat Feb 6 2021
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
void delay(int a);
void main(void)
 { 
    int i;
    char a[10]={0x3f,0x06,0x5b,0x4f,0x66,0x6d,0x7d,0x07,0x7f,0x6f};
    P3=0x00;
   while (1)
   {
      for(i=0;i<10;i++)
      {
	 P3=a[i];
	 delay(10);
      }
   }
 }
 void delay(int a)
 {
    int i;
    int j;
    for(i=0;i<a;i++)
    {
       for(j=0;j<10000;j++)
       {
       }
    }
 }