/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Feb 16 2021
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
sbit led1 = P2^0;
sbit led2 = P2^1;
sbit led3 = P2^2;
sbit led4 = P2^3;
void ISR_ex0(void);
void Delay();
void main()
 { 
   // Write your code here
    P0=0x00;
    P1=0x00;
    P2=0x00;
    P3=0x04;
    IE=0x81;
    IT0=1;
   while (1)
      {
      led1=1;
      led2=0;
      led3=1;
      led4=0;
 }
 }
 void ISR_ex0(void) interrupt 0
 {
    led1=~led1;
    led2=~led2;
    led3=~led3;
    led4=~led4;
    Delay();
 }
 void Delay(){
    int i;
    TMOD=0x01;
    for(i=0;i<500;i++)
       {
       TH0=0xF8;
       TL0=0xCC;
       TR0=1;
       while(TF0==0);
	  TR0=0;
	  TF0=0;
       }
 }